### ISSUE TITLE
LSM9DS0 discontinued

### ISSUE THREAD

**Issue by fiploss** [kervi/kervi#9]
St Micro's LSM9DS0 has been discontinued.  Would it be possible to have the driver for the LSM9DS1 integrated in this project?

**Comment by kervi** [comment]
No problem :-), I have just ordered one, expect a few weeks before it is added to the library.

**Comment by fiploss** [comment]
Thank you for the quick response.

We tried to run the picamera today and received the following error:

pi@raspberrypi:~ $ python3 myapp.py
Starting kervi application 
   kervi version: 0.20.15 
   platform driver: kervi.platforms.raspberry 
   IPC address: tcp://192.168.222.161:45631 
   load plugin: kervi.plugin.storage.sqlite_temp 
   load plugin: kervi.plugin.storage.sqlite 
   load plugin: kervi.plugin.authentication.plain 
   load plugin: kervi.plugin.messaging.user_log 
ERROR    MainProcess CameraFrameThread 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kervi/vision/camera.py", line 236, in run
    self.camera._capture_frames()
  File "/usr/local/lib/python3.5/dist-packages/kervi/vision/camera.py", line 434, in _capture_frames
    self._device_driver._capture_frames()
AttributeError: 'CameraDriver' object has no attribute '_capture_frames'
wait for ready
   load: controllers 
   load: cams 
   load: controllers 
   load: cams 
   load plugin: kervi.plugin.ui.web 
   load plugin: kervi.plugin.ipc.websocket 
   load: sensors 
   load plugin: kervi.plugin.ui.web 
   load plugin: kervi.plugin.ipc.websocket 
   load: sensors 
Reach your application at http://192.168.222.161:8080 
   start websocket: 192.168.222.161 9000  
   start websocket: 192.168.222.161 9000

**Comment by fiploss** [comment]
Sorry, I closed this by mistake.

**Comment by kervi** [comment]
Sorry for the long delay it took forever to get the sensor from China.
The documentation is not updated yet you can see an working example here
https://github.com/kervi/kervi-tests/blob/master/device-test/sensors/LSM9DS1.py
